services:
  api-pdf:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 81
    expose:
      - "81"
    environment:
      - REDIS_URL=redis://redis-pdf:6379/1
    restart: always
    depends_on:
      - redis-pdf
    volumes:
      - dados_pdfs:/app/uploads

  worker-pdf:
    build: .
    command: celery -A worker.app_celery worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis-pdf:6379/1
    restart: always
    depends_on:
      - redis-pdf
    volumes:
      - dados_pdfs:/app/uploads

  redis-pdf:
    image: redis:alpine
    restart: always

volumes:
  dados_pdfs:
